--- 
 - name: Include OS-specific variables.
   include_vars: "{{ ansible_system }}.yml"

 - name: Include envrionment variables.
   include_vars: "{{ dynatrace_environment}}.yml"

 - name: Check if Dynatrace OneAgent is already installed
   win_stat:
     path: "{{ dynatrace_executable }}"
   register: agent_installed

 - name: Build oneagent install url
   include_tasks: "build-url.yml"
   when: agent_installed.stat.exists == false

 - name: Download Dynatrace OneAgent
   win_get_url:
     url: "{{ oneagent_installer_script_url }}"
     validate_certs: no
     dest: "{{ download_dir }}{{ filename }}"    
   when: agent_installed.stat.exists == false

 - name: Install oneagent
   win_shell: "{{ oneagent_install_command }}"
   when: agent_installed.stat.exists == false
   notify: Start the One Agent Service Windows