--- 
 - name: Include System variables.
   include_vars: "{{ ansible_system }}.yml"

 - name: Check if Dynatrace OneAgent is already installed
   win_stat:
     path: "{{ dynatrace_state }}"
   register: agent_installed

 - name: Download Dynatrace OneAgent dev
   win_get_url:
     url: "{{ oneagent_installer_script_url_latest_dev if oneagent_version_latest == true else oneagent_installer_script_url_versioned_dev }}"
     validate_certs: no
     dest: "{{ download_dir }}{{ filename }}"
   when: agent_installed.stat.exists == false and dynatrace_environment == 'dev'

 - name: Download Dynatrace OneAgent prod
   win_get_url:
     url: "{{ oneagent_installer_script_url_latest_prod if oneagent_version_latest == true else oneagent_installer_script_url_versioned_prod }}"
     validate_certs: no
     dest: "{{ download_dir }}{{ filename }}"
   when: agent_installed.stat.exists == false and dynatrace_environment == 'prod'

 - name: install oneagent
   win_shell: "{{ oneagent_install_command }}"
   when: agent_installed.stat.exists == false

 - name: Start the One Agent Service
   win_service:
     name: "{{ service_name }}"
     state: started
   when: agent_installed.stat.exists == false